[package]
name = "updater"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }
colored = "2.0"
indicatif = "0.17"
zip = "2"
serde_json = "1.0"
